package com.silasonyango.transactionservice.services.excel;

public enum ExcelServiceEnum {
    FEE_BALANCES_PER_CLASS,
    FEE_BALANCES_PER_LOT,
    STUDENTS_PER_LOT,
    STUDENT_PER_CLASS_STREAM,
    LOT_FEE_BALANCE_WITH_TERM_BALANCE_THRESHOLD,
    CLASS_STREAM_FEE_BALANCE_WITH_TERM_BALANCE_THRESHOLD,
    FEE_INSTALLMENTS_MADE_TODAY
}
