apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: uat
  name: waondo-transaction-service
  annotations:
    kubernetes.io/ingress.class: nginx
#    certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
    - host: transaction.waondo.agweria.com
      http:
        paths:
          - path: /
            backend:
              serviceName: waondo-transaction-service
              servicePort: 8080